-- 코드를 입력하세요

-- SELECT DISTINCT A.AUTHOR_ID, A.AUTHOR_NAME
-- FROM AUTHOR A LEFT JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID;

SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM (BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID) LEFT JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
GROUP BY CATEGORY, AUTHOR_NAME, A.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC;
