-- 코드를 입력하세요
SELECT ORDER_ID, PRODUCT_ID, TO_CHAR(OUT_DATE, 'yyyy-MM-DD') OUT_DATE,
CASE
    WHEN TO_CHAR(OUT_DATE, 'MMDD') > '0501' THEN '출고대기'
    WHEN TO_CHAR(OUT_DATE, 'MMDD') <= '0501' THEN '출고완료'
    WHEN OUT_DATE IS NULL THEN '출고미정'
END AS "출고여부"
FROM FOOD_ORDER
ORDER BY 1;