-- 코드를 입력하세요
WITH TOTAL AS
(
    SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) TOT
    FROM OFFLINE_SALE A INNER JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY PRODUCT_CODE
)

SELECT A.PRODUCT_CODE, (TOT * PRICE) SALES
FROM TOTAL A INNER JOIN PRODUCT B ON A.PRODUCT_CODE = B.PRODUCT_CODE
ORDER BY 2 DESC, 1;
