-- 코드를 입력하세요
WITH CNT AS 
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT PRODUCT_CODE, (TOT * PRICE) SALES
FROM CNT A LEFT OUTER JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 2 DESC, 1;