-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (SELECT A.ANIMAL_ID, A.NAME, (B.DATETIME - A.DATETIME) AS DATETIME
      FROM ANIMAL_INS A LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
      WHERE B.DATETIME IS NOT NULL
      ORDER BY DATETIME DESC)
WHERE ROWNUM <= 2;