-- 코드를 입력하세요
-- 조건에 부합하는 대여 가능한 차 정보만 가진 테이블
WITH USED AS
(
    SELECT A.CAR_ID, CAR_TYPE, DAILY_FEE
    FROM (SELECT CAR_ID, MAX(TO_CHAR(END_DATE, 'YYYYMMDD')) LATEST
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          GROUP BY CAR_ID) A INNER JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE LATEST <'20221101' AND CAR_TYPE IN ('세단', 'SUV')
)
    
SELECT A.CAR_ID, A.CAR_TYPE, (DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) FEE
FROM USED A INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상' AND (DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC;