-- 코드를 입력하세요
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM 
    (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE
     FROM REST_REVIEW GROUP BY REST_ID) A
      LEFT OUTER JOIN REST_INFO B ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;