-- 코드를 입력하세요
-- MONTH에 TO_NUMBER 안 씌우면, 월 앞에 '0' 붙음
SELECT TO_CHAR(B.SALES_DATE, 'YYYY') YEAR, 
       TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')) MONTH,
       COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
       ROUND(
           COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(USER_ID)
                                            FROM USER_INFO
                                           WHERE TO_CHAR(JOINED, 'YYYY') = '2021')
           , 1) AS PURCHASED_RATIO
 FROM (SELECT * FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021') A
        INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
 GROUP BY TO_CHAR(B.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM'))
 ORDER BY YEAR, MONTH;