-- 코드를 입력하세요
WITH ANI AS
(
    SELECT NAME, DATETIME
    FROM ANIMAL_INS
    WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID
                            FROM ANIMAL_OUTS)
)

SELECT * 
FROM ANI
ORDER BY DATETIME
FETCH FIRST 3 ROWS ONLY;