-- 코드를 입력하세요
WITH TRUCK AS
(
    SELECT HISTORY_ID, CAR_TYPE, DAILY_FEE, (END_DATE - START_DATE + 1) DURATION,
    CASE
        WHEN (END_DATE - START_DATE + 1) >= 90 THEN '90일 이상'
        WHEN (END_DATE - START_DATE + 1) >= 30 THEN '30일 이상'
        WHEN (END_DATE - START_DATE + 1) >= 7 THEN '7일 이상'
        ELSE NULL
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A INNER JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, (DURATION * DAILY_FEE * (100 - NVL(DISCOUNT_RATE,0)) / 100) FEE
FROM TRUCK A LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
        ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;