-- 코드를 입력하세요
WITH APNT AS 
(
    SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE TO_CHAR(APNT_YMD,'YYYY-MM-DD')='2022-04-13' AND APNT_CNCL_YN = 'N' 
)

SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, APNT_YMD
FROM (APNT A INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO) INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
ORDER BY 6;