-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER A LEFT JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
                                  FROM USED_GOODS_BOARD
                                  WHERE STATUS = 'DONE'
                                  GROUP BY WRITER_ID) B ON A.USER_ID = B.WRITER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY 3;