-- 코드를 입력하세요
WITH TARGET AS
(
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD 
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)
 
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM TARGET A INNER JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
ORDER BY 2 DESC;