-- 코드를 입력하세요
-- TO_NUMBER를 안해주면 HOUR에서 09로 출력되어 오류 발생
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME,'HH24') BETWEEN '09' AND '19'
GROUP BY TO_CHAR(DATETIME,'HH24')
ORDER BY HOUR;