-- 코드를 입력하세요

-- SELECT *
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) >= 8
--              AND TO_NUMBER(TO_CHAR(END_DATE, 'FMMM')) < 11
--              AND CAR_ID = 23

SELECT TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) BETWEEN 8 AND 10
                GROUP BY CAR_ID
                HAVING COUNT(CAR_ID) >= 5)
      AND TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) BETWEEN 8 AND 10      
GROUP BY CAR_ID, TO_NUMBER(TO_CHAR(START_DATE, 'FMMM'))
ORDER BY 1, 2 DESC;