-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID,
       TO_CHAR(START_DATE, 'YYYY-MM-DD') START_DATE,
       TO_CHAR(END_DATE, 'YYYY-MM-DD') END_DATE,
       CASE WHEN RENT_TYPE >= 30 THEN '장기 대여'
                ELSE '단기 대여'
       END RENT_TYPE
FROM (SELECT HISTORY_ID, CAR_ID,
             START_DATE,
             END_DATE,
             END_DATE - START_DATE + 1 AS RENT_TYPE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE TO_CHAR(START_DATE, 'YYYY-MM') = '2022-09'
     ) 
ORDER BY 1 DESC;