-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR B 
        ON A.CAR_ID = B.CAR_ID
WHERE TO_CHAR(START_DATE, 'MM') = 10 AND CAR_TYPE = '세단'
ORDER BY 1 DESC;