-- 코드를 작성해주세요
SELECT SUM(SCORE) SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES A LEFT OUTER JOIN HR_DEPARTMENT B ON A.DEPT_ID = B.DEPT_ID LEFT OUTER JOIN HR_GRADE C ON C.EMP_NO = A.EMP_NO
WHERE A.EMP_NO = (SELECT EMP_NO
                 FROM HR_GRADE
                 GROUP BY EMP_NO
                 ORDER BY SUM(SCORE) DESC
                 LIMIT 1)
GROUP BY A.EMP_NO;