-- 코드를 작성해주세요
SELECT COUNT(TIME) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM (SELECT ID, FISH_TYPE,
      CASE 
        WHEN LENGTH IS NULL THEN 10
        WHEN LENGTH <= 10 THEN 10
        WHEN LENGTH > 10 THEN LENGTH
      END AS 'LENGTH',TIME
     FROM FISH_INFO) FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) > 33
ORDER BY 3;