-- 코드를 작성해주세요
WITH FE AS (SELECT SUM(CODE)
            FROM SKILLCODES
            WHERE CATEGORY LIKE 'Front%')

SELECT CASE 
    WHEN SKILL_CODE & (SELECT * FROM FE) > 0
        AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'python') > 0
        THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
        THEN 'B'
    WHEN SKILL_CODE & (SELECT * FROM FE) > 0
        THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS
GROUP BY GRADE, ID, EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;